aliases:
  //wing: 132^nd^ Virtual Wing
  //etcher: "132nd-etcher"
  //ovgme: OvGME
  //617: 617^th^ DAMBUSTERS
  //696: 696^th^ TURNSKINS
  //176: 176^th^ EYES OF THE NORTH
  //23: 23^rd^ ARCTIC FOXES
  //259: 259^th^ POLAR BEARS
  //765: 765^th^ THE DREAD PANTHERS
  //all_logos: "[logo617th.png,logo23rd.png,logo259th.png,logo696th.png,logo176th.png,logo765th.png]"